export enum TokenType {
  VERIFICATION_TOKEN = 'VERIFICATION_TOKEN',
  PASSWORD_RESET_TOKEN = 'PASSWORD_RESET_TOKEN',
  CHANGE_PASSWORD_TOKEN = 'CHANGE_PASSWORD_TOKEN',
  CHANGE_EMAIL_TOKEN = 'CHANGE_EMAIL_TOKEN',
  TWO_FA_VERIFICATION_TOKEN = 'TWO_FA_VERIFICATION_TOKEN',
  VERIFY_PHONE_NUMBER_TOKEN = 'VERIFY_PHONE_NUMBER_TOKEN',
  VERIFY_QR_TOKEN = 'VERIFY_QR_TOKEN',
  LOGIN_WITH_PHONE_NUMBER_TOKEN = 'LOGIN_WITH_PHONE_NUMBER_TOKEN',
}
