export enum TokenType {
  VERIFICATION_TOKEN = 'VERIFICATION_TOKEN',
  PASSWORD_RESET_TOKEN = 'PASSWORD_RESET_TOKEN',
  CHANGE_PASSWORD_TOKEN = 'CHANGE_PASSWORD_TOKEN',
  CHANGE_EMAIL_TOKEN = 'CHANGE_EMAIL_TOKEN',
  PHONE_TWO_FA_VERIFICATION_TOKEN = 'PHONE_TWO_FA_VERIFICATION_TOKEN',
  QR_TWO_FA_VERIFICATION_TOKEN = 'QR_TWO_FA_VERIFICATION_TOKEN',
  VERIFY_PHONE_NUMBER_TOKEN = 'VERIFY_PHONE_NUMBER_TOKEN',
  LOGIN_WITH_PHONE_NUMBER_TOKEN = 'LOGIN_WITH_PHONE_NUMBER_TOKEN',
  PASSWORDLESS_LOGIN_TOKEN = 'PASSWORDLESS_LOGIN_TOKEN',
}
