# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
      production-patch:
        dependency-type: production
        update-types:
          - patch
        exclude-patterns:
          - "@aws-sdk/*"
    ignore:
      - dependency-name: graphql
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"
