//AUTH USERS
export const ADD_AUTH_USERS = 'ADD_AUTH_USERS';
export const START_AUTH_USERS_LOADING = 'START_AUTH_USERS_LOADING';
export const STOP_AUTH_USERS_LOADING = 'STOP_AUTH_USERS_LOADING';
export const SET_AUTH_USERS_ERROR = 'SET_AUTH_USERS_ERROR';

//AUTHORIZATION
export const SET_AUTHENTICATION_TOKEN = 'SET_AUTHENTICATION_TOKEN';
export const SET_AUTH_USERS_SUCCESS = 'SET_AUTH_USERS_SUCCESS';
export const DELETE_USER_ACTION = 'DELETE_USER_ACTION';
export const SEARCH_USERS = 'SEARCH_USERS';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const INCREASE_COUNT = 'INCREASE_COUNT';
export const EDIT_USER_ACTION = 'EDIT_USER_ACTION';
export const EDIT_USER = 'EDIT_USER';
export const BLOCK_USER_UI = 'BLOCK_USER_UI';
export const UNBLOCK_USER_UI = 'UNBLOCK_USER_UI';
export const SET_AUTHENTICATION_TOKEN_ERROR = 'SET_AUTHENTICATION_TOKEN_ERROR';
export const START_AUTHENTICATION_LOADING = 'START_AUTHENTICATION_LOADING';
export const STOP_AUTHENTICATION_LOADING = 'STOP_AUTHENTICATION_LOADING';
export const CLEAR_AUTHENTICATION_TOKEN = 'CLEAR_AUTHENTICATION_TOKEN';
export const SET_ADMIN_MODULES = 'SET_ADMIN_MODULES';

//AUTH CONFIG
export const SET_AUTHENTICATION_CONFIG = 'SET_AUTHENTICATION_CONFIG';
export const START_AUTHENTICATION_CONFIG_LOADING = 'START_AUTHENTICATION_CONFIG_LOADING';
export const STOP_AUTHENTICATION_CONFIG_LOADING = 'STOP_AUTHENTICATION_CONFIG_LOADING';
export const SET_AUTHENTICATION_CONFIG_ERROR = 'SET_AUTHENTICATION_CONFIG_ERROR';
export const CLEAR_AUTH_PAGE_STORE = 'CLEAR_AUTH_PAGE_STORE';

//EMAILS
export const SET_EMAIL_TEMPLATES = 'SET_EMAIL_TEMPLATES';
export const SET_EMAIL_SETTINGS = 'SET_EMAIL_SETTINGS';
export const START_EMAIL_LOADING = 'START_EMAIL_LOADING';
export const STOP_EMAIL_LOADING = 'STOP_EMAIL_LOADING';
export const SET_EMAIL_ERROR = 'SET_EMAIL_ERROR';
export const UPDATE_EMAIL_TEMPLATE = 'UPDATE_EMAIL_TEMPLATE';
export const ADD_EMAIL_TEMPLATE = 'ADD_EMAIL_TEMPLATE';
export const CLEAR_EMAIL_PAGE_STORE = 'CLEAR_EMAIL_PAGE_STORE';

/** Notification Types **/
export const SET_NOTIFICATION_CONFIG = 'SET_NOTIFICATION_CONFIG';
export const PUT_NOTIFICATION_CONFIG = 'PUT_NOTIFICATION_CONFIG';
export const START_NOTIFICATION_LOADING = 'START_NOTIFICATION_LOADING';
export const STOP_NOTIFICATION_LOADING = 'STOP_NOTIFICATION_LOADING';
export const SET_NOTIFICATION_ERROR = 'SET_NOTIFICATION_ERROR';
export const CLEAR_NOTIFICATION_PAGE_STORE = 'CLEAR_NOTIFICATION_PAGE_STORE';

/** STORAGE CONFIG **/
export const SET_STORAGE_CONFIG = 'SET_STORAGE_CONFIG';
export const START_STORAGE_LOADING = 'START_STORAGE_LOADING';
export const STOP_STORAGE_LOADING = 'STOP_STORAGE_LOADING';
export const SET_STORAGE_ERROR = 'SET_STORAGE_ERROR';
export const CLEAR_STORAGE_PAGE_STORE = 'CLEAR_STORAGE_PAGE_STORE';

//CMS

export const SET_CMS_MORE_SCHEMAS = 'SET_CMS_MORE_SCHEMAS';

export const SET_CMS_SCHEMAS = 'SET_CMS_SCHEMAS';
export const START_CMS_LOADING = 'START_CMS_LOADING';
export const STOP_CMS_LOADING = 'STOP_CMS_LOADING';
export const SET_CMS_ERROR = 'SET_CMS_ERROR';
export const SET_SELECTED_SCHEMA = 'SET_SELECTED_SCHEMA';
export const CLEAR_SELECTED_SCHEMA = 'CLEAR_SELECTED_SCHEMA';
export const UPDATE_SCHEMAS_STATUS = 'UPDATE_SCHEMAS_STATUS';
export const DELETE_CMS_SCHEMAS = 'DELETE_CMS_SCHEMAS';
export const SET_CMS_SCHEMA_DOCUMENTS = 'SET_CMS_SCHEMA_DOCUMENTS';
export const SET_CUSTOM_ENDPOINTS = 'SET_CUSTOM_ENDPOINTS';
export const SET_MORE_DOCUMENTS_BY_NAME = 'SET_MORE_CMS_SCHEMA_DOCUMENTS_BY_NAME';

//SETTINGS
export const SET_AVAILABLE_CLIENTS = 'SET_AVAILABLE_CLIENTS';
export const APPEND_NEW_CLIENT = 'APPEND_NEW_CLIENT';
export const DELETE_CLIENT = 'DELETE_CLIENT';
export const START_SETTINGS_LOADING = 'START_SETTINGS_LOADING';
export const STOP_SETTINGS_LOADING = 'STOP_SETTINGS_LOADING';
export const SET_SETTINGS_ERROR = 'SET_SETTINGS_ERROR';

//CUSTOM ENDPOINTS
export const SET_SELECTED_ENDPOINT = 'SET_SELECTED_ENDPOINT';
export const SET_ENDPOINT_DATA = 'SET_ENDPOINT_DATA';
export const SET_SCHEMA_FIELDS = 'SET_SCHEMA_FIELDS';
export const ENDPOINT_CLEAN_SLATE = 'ENDPOINT_CLEAN_SLATE';
