version: "3.9"
services:
  redis:
    image: redis

  core:
    image: "ghcr.io/conduitplatform/conduit:${IMAGE_TAG}"
    ports:
      - "55152:55152"
      - "3000:3000"
      - "3001:3001"
    links:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"

  database-provider:
    image: "ghcr.io/conduitplatform/conduit-database:${IMAGE_TAG}"
    ports:
      - "55153:55153"
    links:
      - core
    depends_on:
      - core
    environment:
      databaseURL: "${_MONGO_URL}"
      SERVICE_URL: 0.0.0.0:55153
      REGISTER_NAME: 'true'
      CONDUIT_SERVER: core:55152

  authentication:
    image: "ghcr.io/conduitplatform/conduit-authentication:${_IMAGE_TAG}"
    ports:
      - "5000:5000"
    depends_on:
      - database-provider
    links:
      - core
    environment:
      CONDUIT_SERVER: core:55152

  # admin:
  #   image: ghcr.io/conduitplatform/conduit-admin:${__IMAGE_tAG}
  #   links:
  #     - core
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - authentication
  #   environment:
  #     CONDUIT_API: core:3000
  #     CONDUIT_URL: admin:8080
  #     MASTER_KEY: M4ST3RK3Y
