global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 3s
    scrape_timeout: 3s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - labels:
          module: 'Core'
        targets: ['conduit:9091']
      - labels:
          module: 'Database'
        targets: ['conduit-database:9092']
      - labels:
          module: 'Router'
        targets: ['conduit-router:9093']
      - labels:
          module: 'Authentication'
        targets: ['conduit-authentication:9094']
      - labels:
          module: 'Chat'
        targets: ['conduit-chat:9095']
      - labels:
          module: 'Email'
        targets: ['conduit-email:9096']
      - labels:
          module: 'Forms'
        targets: ['conduit-forms:9097']
      - labels:
          module: 'Push Notifications'
        targets: ['conduit-push-notifications:9098']
      - labels:
          module: 'SMS'
        targets: ['conduit-sms:9099']
      - labels:
          module: 'Storage'
        targets: ['conduit-storage:9190']
