//AUTH USERS
export const ADD_AUTH_USERS = 'ADD_AUTH_USERS';
export const START_AUTH_USERS_LOADING = 'START_AUTH_USERS_LOADING';
export const STOP_AUTH_USERS_LOADING = 'STOP_AUTH_USERS_LOADING';
export const SET_AUTH_USERS_ERROR = 'SET_AUTH_USERS_ERROR';

//AUTHORIZATION
export const SET_AUTHENTICATION_TOKEN = 'SET_AUTHENTICATION_TOKEN';
export const SET_AUTHENTICATION_TOKEN_ERROR = 'SET_AUTHENTICATION_TOKEN_ERROR';
export const START_AUTHENTICATION_LOADING = 'START_AUTHENTICATION_LOADING';
export const STOP_AUTHENTICATION_LOADING = 'STOP_AUTHENTICATION_LOADING';
export const CLEAR_AUTHENTICATION_TOKEN = 'CLEAR_AUTHENTICATION_TOKEN';

//AUTH CONFIG
export const SET_AUTHENTICATION_CONFIG = 'SET_AUTHENTICATION_CONFIG';
export const START_AUTHENTICATION_CONFIG_LOADING = 'START_AUTHENTICATION_CONFIG_LOADING';
export const STOP_AUTHENTICATION_CONFIG_LOADING = 'STOP_AUTHENTICATION_CONFIG_LOADING';
export const SET_AUTHENTICATION_CONFIG_ERROR = 'SET_AUTHENTICATION_CONFIG_ERROR';
export const CLEAR_AUTH_PAGE_STORE = 'CLEAR_AUTH_PAGE_STORE';

//EMAILS
export const SET_EMAIL_TEMPLATES = 'SET_EMAIL_TEMPLATES';
export const SET_EMAIL_SETTINGS = 'SET_EMAIL_SETTINGS';
export const START_EMAIL_LOADING = 'START_EMAIL_LOADING';
export const STOP_EMAIL_LOADING = 'STOP_EMAIL_LOADING';
export const SET_EMAIL_ERROR = 'SET_EMAIL_ERROR';
export const UPDATE_EMAIL_TEMPLATE = 'UPDATE_EMAIL_TEMPLATE';
export const ADD_EMAIL_TEMPLATE = 'ADD_EMAIL_TEMPLATE';

/** Notification Types **/
export const SET_NOTIFICATION_CONFIG = 'SET_NOTIFICATION_CONFIG';
export const PUT_NOTIFICATION_CONFIG = 'PUT_NOTIFICATION_CONFIG';
export const START_NOTIFICATION_LOADING = 'START_NOTIFICATION_LOADING';
export const STOP_NOTIFICATION_LOADING = 'STOP_NOTIFICATION_LOADING';
export const SET_NOTIFICATION_ERROR = 'SET_NOTIFICATION_ERROR';
