export const ADD_AUTH_USERS = 'ADD_AUTH_USERS';
export const START_AUTH_USERS_LOADING = 'START_AUTH_USERS_LOADING';
export const STOP_AUTH_USERS_LOADING = 'STOP_AUTH_USERS_LOADING';
export const SET_AUTH_USERS_ERROR = 'SET_AUTH_USERS_ERROR';
