export const ADD_AUTH_USERS = 'ADD_AUTH_USERS';
export const START_AUTH_USERS_LOADING = 'START_AUTH_USERS_LOADING';
export const STOP_AUTH_USERS_LOADING = 'STOP_AUTH_USERS_LOADING';
export const SET_AUTH_USERS_ERROR = 'SET_AUTH_USERS_ERROR';

export const SET_AUTHENTICATION_TOKEN = 'SET_AUTHENTICATION_TOKEN';
export const SET_AUTHENTICATION_TOKEN_ERROR = 'SET_AUTHENTICATION_TOKEN_ERROR';
export const START_AUTHENTICATION_LOADING = 'START_AUTHENTICATION_LOADING';
export const STOP_AUTHENTICATION_LOADING = 'STOP_AUTHENTICATION_LOADING';
export const CLEAR_AUTHENTICATION_TOKEN = 'CLEAR_AUTHENTICATION_TOKEN';
