on:
  push:
    branches:
      - main
    paths:
      - "packages/**"
      - "libraries/grpc-sdk/**"
      - "libraries/hermes/**"

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    name: Build core
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build conduit core
        run: |
          DEV=TRUE make conduit
