on:
  push:
    branches:
      - master
    paths:
      - "modules/database/**"
      - "libraries/grpc-sdk/**"
jobs:
  deploy:
    runs-on: ubuntu-18.04
    name: Build database
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build conduit database
        run: |
          DEV=TRUE make modules/database
