on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy conduit
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: ${{ secrets.REGISTRY }}
          repository: conduit
          tags: latest
  document:
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v2
        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: '10.x'
        - name: Cache dependencies
          uses: actions/cache@v1
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
                  ${{ runner.os }}-node-
        - run: yarn install --frozen-lockfile
        - run: yarn run docz:build
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GIT_TOKEN }}
            publish_dir: ./docs
