on:
  push:
    branches:
      - main
    paths:
      - "modules/functions/**"
      - "libraries/grpc-sdk/**"

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    name: Build chat
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build conduit chat
        run: |
          DEV=TRUE make modules/functions
