on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "modules/sms/**"
      - "libraries/grpc-sdk/**"
      - "libraries/module-tools/**"

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    name: Build sms
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build conduit sms
        run: |
          DEV=TRUE make modules/sms
